#!/bin/bash

# Running this script deletes the files generated by this example

rm -f echo03_vars02_fvars03_1_1.completed
rm -f echo03_vars02_fvars03_1_1.error
rm -f echo03_vars02_fvars03_1_1.lsf
rm -f echo03_vars02_fvars03_1_1.output
rm -f echo03_vars02_fvars03_1.log
rm -f echo03_vars02_fvars03_1.summary
rm -f echo03_vars02_fvars03_2_2.completed
rm -f echo03_vars02_fvars03_2_2.error
rm -f echo03_vars02_fvars03_2_2.lsf
rm -f echo03_vars02_fvars03_2_2.output
rm -f echo03_vars02_fvars03_2.log
rm -f echo03_vars02_fvars03_2.summary
rm -f echo03_vars02_fvars03_3_3.completed
rm -f echo03_vars02_fvars03_3_3.error
rm -f echo03_vars02_fvars03_3_3.lsf
rm -f echo03_vars02_fvars03_3_3.output
rm -f echo03_vars02_fvars03_3.log
rm -f echo03_vars02_fvars03_3.summary
rm -f echo03_vars02_fvars03.list-jobs
rm -f echo03_vars02_fvars03.list-jobs.submitted
rm -f echo03_vars02_fvars03.list-summaries
rm -f outfile1.txt
rm -f outfile2.txt
rm -f outfile3.txt
