#!/bin/bash

# Running this script deletes the files generated by this example

rm -f echo02_vars02_A_1_1.completed
rm -f echo02_vars02_A_1_1.error
rm -f echo02_vars02_A_1_1.lsf
rm -f echo02_vars02_A_1_1.output
rm -f echo02_vars02_A_1.log
rm -f echo02_vars02_A_1.summary
rm -f echo02_vars02_A.list-jobs
rm -f echo02_vars02_A.list-jobs.submitted
rm -f echo02_vars02_A.list-summaries
rm -f example_02_output.txt

rm -f echo02_vars02_B_1_1.completed
rm -f echo02_vars02_B_1_1.error
rm -f echo02_vars02_B_1_1.lsf
rm -f echo02_vars02_B_1_1.output
rm -f echo02_vars02_B_1.log
rm -f echo02_vars02_B_1.summary
rm -f echo02_vars02_B.list-jobs
rm -f echo02_vars02_B.list-jobs.submitted
rm -f echo02_vars02_B.list-summaries
rm -f example_02_output.txt
