#!/bin/bash

#BSUB -w 'ended("JOBDATE0_000000_jobID0000_root")'
#BSUB -J JOBDATE0_000000_jobID0000_first
#BSUB -e JOBDATE0_000000_jobID0000_first.error
#BSUB -o JOBDATE0_000000_jobID0000_first.output


# Job file variables:
JSUB_PATH_TO_THIS_JOB=<to-be-replaced-by-the-path-to-this-file>
JSUB_JOB_ID="jobID0000_first"
JSUB_LOG_FILE="jlang_function_test_files/job_files/jobID0000.log"
JSUB_SUMMARY_COMPLETED="jlang_function_test_files/job_files/JOBDATE0_000000_jobID0000_first.completed"
JSUB_SUMMARY_INCOMPLETE="jlang_function_test_files/job_files/JOBDATE0_000000_jobID0000_first.incomplete"
JSUB_VERSION_CONTROL=true
JSUB_JOB_TIMESTAMP=true

# Contents inserted from other files (this section is intended to be used only for functions):

# --- From file: jlang_function_test_files/dummy_bash_functions/dummy1.sh
function dummy1 {
echo Running_dummy_function_1
}

# --- From file: jlang_function_test_files/dummy_bash_functions/dummy2.sh
function dummy2 {
echo Running_dummy_function_2
}
function dummy2_1 {
echo Running_dummy_function_2_1
}
function dummy2_2 {
echo Running_dummy_function_2_2
}

# --- From file: jlang_function_test_files/dummy_bash_functions/dummy3.sh
function dummy3 {
echo Running_dummy_function_3
}

# --- From file: jlang_function_test_files/dummy_bash_functions/jcheck_resume.sh
contents of jcheck_resume.sh


initialise_job
# Commands taken from summary file: dir/name/is/ignored/jobID0000.summary
#JSUB<begin-job>
check_completion "jlang_function_test_files/job_files/JOBDATE0_000000_jobID0000_root.completed"
#JGROUP first
bash echo "cmd 12"
jcheck_resume
dummy10_1 arg1_1 arg2_1
bash echo "cmd 13"

#JSUB<finish-job>
process_job
on_completion
