#!/bin/bash

#BSUB -J JOBDATE0_000000_jobID0000_root
#BSUB -e JOBDATE0_000000_jobID0000_root.error
#BSUB -o JOBDATE0_000000_jobID0000_root.output

sleep 7.7


# Job file variables:
JSUB_PATH_TO_THIS_JOB=<to-be-replaced-by-the-path-to-this-file>
JSUB_JOB_ID="jobID0000_root"
JSUB_LOG_FILE="jlang_function_test_files/job_files/ut_create_jobs_from_summary.log"
JSUB_SUMMARY_COMPLETED="jlang_function_test_files/job_files/ut_create_jobs_from_summary_root.completed"
JSUB_SUMMARY_INCOMPLETE="jlang_function_test_files/job_files/ut_create_jobs_from_summary_root.incomplete"
JSUB_VERSION_CONTROL=true
JSUB_JOB_TIMESTAMP=true

# Contents inserted from other files (this section is intended to be used only for functions):

# --- From file: jlang_function_test_files/dummy_bash_functions/dummy1.sh
function dummy1 {
echo Running_dummy_function_1
}

# --- From file: jlang_function_test_files/dummy_bash_functions/dummy2.sh
function dummy2 {
echo Running_dummy_function_2
}
function dummy2_1 {
echo Running_dummy_function_2_1
}
function dummy2_2 {
echo Running_dummy_function_2_2
}

# --- From file: jlang_function_test_files/dummy_bash_functions/dummy3.sh
function dummy3 {
echo Running_dummy_function_3
}

# --- From file: jlang_function_test_files/dummy_bash_functions/jcheck_resume.sh
contents of jcheck_resume.sh


# Commands taken from summary file: dir/name/is/ignored/ut_create_jobs_from_summary.summary

#JSUB<begin-job>
# This data would come from reading summary files.
#JSUB<summary-name>ProtocolName
bash echo "cmd 01"
jcheck_resume
bash echo "cmd 02"
dummy10 arg1 arg2
bash echo "cmd 03"

#JSUB<finish-job>
process_job
