#!/bin/bash

# Running this script deletes the files generated by this example

rm -rf dummy_output
rm -rf jobs
rm -rf lsf_out
rm -rf progoress
rm -rf summaries
rm -f dummy_data/data_2B.txt # The input file that is supposed to be missing in the first run of example 7 and is then placed in the dummy_data directory for the second run
rm -rf re_jobs
rm -rf re_lsf_out
rm -rf re_progoress
rm -f resumed.list-summaries