#!/bin/bash

# Running this script deletes the files generated by this example

rm -rf jobs
rm -rf lsf_out
rm -rf progoress
rm -rf results_Anum1.txt
rm -rf results_Anum2.txt
rm -rf results_Bnum1.txt
rm -rf results_Bnum2.txt
rm -rf summaries
