#!/bin/bash

# Running this script deletes the files generated by example 1

rm -f echo_1_1.completed
rm -f echo_1_1.error
rm -f echo_1_1.lsf
rm -f echo_1_1.output
rm -f echo_1.log
rm -f echo_1.summary
rm -f echo.list-jobs
rm -f echo.list-jobs.submitted
rm -f echo.list-summaries
rm -f example_01_output.txt
