#!/bin/bash

# Running this script deletes the files generated by this example

rm -rf jobs
rm -rf lsf_out
rm -rf outfile1.txt
rm -rf outfile2.txt
rm -rf outfile3.txt
rm -rf progoress
rm -rf summaries

